### ISSUE TITLE
can not install mpdlcd on RuneAudio(ArchLinux) in UTF-8 environment

### ISSUE THREAD

**Issue by hondalo** [rbarrois/mpdlcd#16]
## Dear Sir, at title, I can not install mpdlcd (via pip install mpdlcd or pip install <URL>) in UTF-8 Chinese environment, error message as below. I am new beginner of Python and just want to use mpdlcd on RuneAudio, anyone can help me to solve this problem? thanks

Using cached mpdlcd-0.4.0.tar.gz
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-xrkoif83-build/setup.py", line 45, in <module>
        version=get_version(PACKAGE),
      File "/tmp/pip-xrkoif83-build/setup.py", line 19, in get_version
        for line in f:
      File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 55: ordinal not in range(128)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

```
  File "<string>", line 20, in <module>

  File "/tmp/pip-xrkoif83-build/setup.py", line 45, in <module>

    version=get_version(PACKAGE),

  File "/tmp/pip-xrkoif83-build/setup.py", line 19, in get_version

    for line in f:

  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode

    return codecs.ascii_decode(input, self.errors)[0]

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 55: ordinal not in range(128)

----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-xrkoif83-build
```

**Comment by rbarrois** [comment]
Hi!

Thanks for the report.

This should be fixed in version 0.4.1, that I've just released.
Could you try again, and let me know if this has fixed the problem?

Thanks!

**Comment by hondalo** [comment]
Dear Sir,
        I am in UTF-8 environment, after ver. 0.4.1, install is ok, but I got error message when I want to run mpdlcd in RuneAudio(ArchLinux), error message as below, could U help to check (I am the beginner on Linux)
PS1. it works well in Volumio(Raspbian) now. so I guess maybe is the difference between Debian & Arch ?
PS2. why mpdlcd will call lcdproc ver0.3 ? it already be upgraded to 0.5.7 ?
PS3. I did the same install, but Raspbian install mpdlcd in Python 2.7, and Arch install mpdlcd in Python3.4, why ?
------
[root@runeaudio systemd]# LCDd
[root@runeaudio systemd]# lcdproc
[root@runeaudio systemd]# mpdlcd
Traceback (most recent call last):
  File "/usr/bin/mpdlcd", line 7, in <module>
    from mpdlcd import cli
  File "/usr/lib/python3.4/site-packages/mpdlcd/cli.py", line 19, in <module>
    from . import lcdrunner
  File "/usr/lib/python3.4/site-packages/mpdlcd/lcdrunner.py", line 8, in <module>
    from lcdproc import server
  File "/usr/lib/python3.4/site-packages/lcdproc/server.py", line 46
    if self.debug: print "Telnet Request:  %s" % (command_string)
                                             ^
SyntaxError: invalid syntax
-----

**Comment by rbarrois** [comment]
Well, you're out of luck: ``mpdlcd`` uses the ``lcdproc`` Python library (https://pypi.python.org/pypi/lcdproc), which isn't compatible with Python3.

So, if archlinux supports python2, you could try to install ``mpdlcd`` through py2; otherwise, you'll have to wait until lcdproc is fully compatible with Py3.

I'll try to craft a pull request to lcdproc for that.

**Comment by hondalo** [comment]
Dear Sir,
        I saw below messages on github, it shows lcdproc maybe can support
python3 ?
        https://github.com/jinglemansweep/lcdproc
-----
LCDproc <https://github.com/jinglemansweep/lcdproc#installing>Installing
<https://github.com/jinglemansweep/lcdproc#python-2>Python 2:

sudo apt-get install python-setuptools
sudo easy_install lcdproc

<https://github.com/jinglemansweep/lcdproc#python-3>Python 3:

sudo apt-get install python3-setuptools
sudo easy_install3 lcdproc

Alternatively, you could use pip to install the package instead of
easy_install.


BR

2015-01-13 4:52 GMT+08:00 Raphaël Barrois <notifications@github.com>:

**Comment by hondalo** [comment]
Dear Sir,
         is it possible when I did 'pip install mpdlcd' command, the
install environment can be limited on Python2 ?

BR

**Comment by rbarrois** [comment]
Hi!

Somewhat late, I've finally ported mpdlcd to Python3 (vendoring lcdproc in the process).

Let me know if you meet any issues ;)
