### ISSUE TITLE
Substituded Characters which are not in the Charset of display

### ISSUE THREAD

**Issue by numer** [rbarrois/mpdlcd#7]
I've several mp3's which have non standard US characters in the id3 fields. This leads to display wrong strings in the LCD.

For example if the title field contains "İyileşiyorum" the LCD display will show "yileiyorum". An other example: "Yanlızlık Senfonisi" is going to be "Yanlzlk Senfonisi".
As you can see the special characters are ignored during display. One solution would be to substitude these characters with there latin counterpart, like ş to s, ğ to g, ı to i, and İ to I. 
An other would be to produce the real character, but I don't know yet if this is possible.

The display I use is a HD44780.

Some info can be found here: http://www.ccsinfo.com/forum/viewtopic.php?t=48459

**Comment by rbarrois** [comment]
Hey there,

This should be fixed with mpdlcd 0.5.x; please reopen the issue if you still have problems!
